# Generated by Django 6.0 on 2026-02-08 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='problem',
            name='examples',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AddField(
            model_name='problem',
            name='starter_code',
            field=models.TextField(blank=True, default='{}'),
        ),
    ]
