# Generated by Django 6.0 on 2026-02-08 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_problem_description_problem_examples_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_leetcode_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='leetcode_handle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verification_token',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
