# Generated by Django 6.0 on 2026-02-08 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userprofile_is_leetcode_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='codechef_handle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='codeforces_handle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_codechef_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_codeforces_verified',
            field=models.BooleanField(default=False),
        ),
    ]
