# Generated by Django 6.0 on 2026-02-08 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_userprofile_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='leetcode_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
