# Generated by Django 6.0 on 2026-02-08 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_problem_leetcode_url_alter_problem_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.URLField(blank=True, default='https://api.dicebear.com/7.x/avataaars/svg?seed=Felix'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='github_link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='linkedin_link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skills',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='twitter_link',
            field=models.URLField(blank=True, default=''),
        ),
    ]
