# Generated by Django 6.0 on 2026-02-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_userprofile_avatar_userprofile_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='constraints',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
