# Generated by Django 6.0 on 2026-02-16 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_context_contextproblem_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='batch',
            field=models.CharField(default='2024', max_length=10),
        ),
    ]
