# Generated by Django 6.0.3 on 2026-03-08 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_testcase_userstats_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('streak', 'Streak'), ('problems', 'Problems Solved'), ('contest', 'Contest'), ('topic', 'Topic Master'), ('speed', 'Speed'), ('special', 'Special')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=50)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-earned_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('leetcode', 'LeetCode'), ('codechef', 'CodeChef'), ('codeforces', 'Codeforces'), ('hackerrank', 'HackerRank'), ('hackerearth', 'HackerEarth'), ('atcoder', 'AtCoder'), ('geeksforgeeks', 'GeeksforGeeks')], max_length=50)),
                ('handle', models.CharField(max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('problems_solved', models.IntegerField(default=0)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('api_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='submission',
            name='code',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='submission',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='submission',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('java', 'Java'), ('cpp', 'C++'), ('javascript', 'JavaScript'), ('c', 'C')], default='python', max_length=20),
        ),
        migrations.AddField(
            model_name='submission',
            name='memory_used_kb',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='test_results',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('ACCEPTED', 'ACCEPTED'), ('FAILED', 'FAILED'), ('RUNTIME_ERROR', 'RUNTIME_ERROR'), ('TIME_LIMIT_EXCEEDED', 'TIME_LIMIT_EXCEEDED'), ('MEMORY_LIMIT_EXCEEDED', 'MEMORY_LIMIT_EXCEEDED'), ('COMPILATION_ERROR', 'COMPILATION_ERROR')], default='PENDING', max_length=25),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['user', 'created_at'], name='api_submiss_user_id_0ecb35_idx'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='platformaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='achievement',
            index=models.Index(fields=['user', 'type'], name='api_achieve_user_id_7d6a65_idx'),
        ),
        migrations.AddIndex(
            model_name='platformaccount',
            index=models.Index(fields=['user', 'platform'], name='api_platfor_user_id_54e148_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='platformaccount',
            unique_together={('user', 'platform')},
        ),
    ]
