# Generated by Django 6.0.3 on 2026-03-08 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_achievement_platformaccount_submission_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('problems', 'Problem Solving'), ('difficulty', 'Difficulty Mastery'), ('topic', 'Topic Mastery'), ('streak', 'Streaks'), ('speed', 'Speed'), ('time', 'Time-based'), ('special', 'Special')], max_length=20)),
                ('requirement', models.JSONField()),
                ('points', models.IntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'points'],
            },
        ),
        migrations.AddField(
            model_name='achievement',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='achievement',
            name='target',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='achievement',
            name='achievement_def',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to='api.achievementdefinition'),
        ),
        migrations.AlterUniqueTogether(
            name='achievement',
            unique_together={('user', 'achievement_def')},
        ),
    ]
