# Generated by Django 4.2.7 on 2026-03-10 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_discussion_discussionreply_alter_achievement_id_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='submission',
            name='unique_accepted_submission',
        ),
    ]
