# Generated by Django 4.2.7 on 2026-03-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_unique_submission_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='points',
            field=models.IntegerField(default=10),
        ),
    ]
