# Generated by Django 4.2.7 on 2026-03-21 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0018_add_points_to_problem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('cn_problems', models.IntegerField(default=0, help_text='Min problems solved on CoderNest')),
                ('cn_score', models.IntegerField(default=0, help_text='Min score on CoderNest')),
                ('lc_problems', models.IntegerField(default=0)),
                ('lc_rating', models.IntegerField(default=0)),
                ('cc_problems', models.IntegerField(default=0)),
                ('cc_rating', models.IntegerField(default=0)),
                ('cf_problems', models.IntegerField(default=0)),
                ('cf_rating', models.IntegerField(default=0)),
                ('target_batch', models.CharField(blank=True, default='All', max_length=50)),
                ('target_branch', models.CharField(blank=True, default='All', max_length=50)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
