# Generated by Django 4.2.7 on 2026-03-22 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_add_gender_hackerrank_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='roll_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
